package com.lms.models.constants;

public enum Specialization {
	  SOFTWARE_ENGINEERING,
	    DATA_SCIENCE,
	    NETWORK_SECURITY,
	    ARTIFICIAL_INTELLIGENCE,
	    WEB_DEVELOPMENT,
	    MOBILE_APP_DEVELOPMENT,
	    DATABASE_MANAGEMENT,
	    CLOUD_COMPUTING,
	    MACHINE_LEARNING,
	    CYBER_SECURITY;
}

